### ISSUE TITLE
fix: zIndex position

### ISSUE THREAD

**Issue by jreydman** [merankori/wallpaper-widget#3]
### Try
```jsx
const container = css`
  display: flex;
  justify-content: center;
  position: relative;
  width: 100vw;
  height: 100vh;
  // FIX make wallpaper as background screen
  z-index: -1;
`;
```

### Result

<img width="1616" alt="image" src="https://github.com/merankori/wallpaper-widget/assets/58705342/62dec0a6-fd31-4f61-9c96-edc0cd0a17d5">

**Comment by jreydman** [comment]
Result:

<img width="692" alt="image" src="https://github.com/merankori/wallpaper-widget/assets/58705342/c04b7493-5f0d-45e9-b404-881837cec418">

**Comment by another1dev** [comment]
Fixed it. Thanks!
